#!/bin/bash
# =============================================================================
# find-wsl-ip.sh — Detect current WSL IP, update .env.local, and print all
# local service URLs. Run any time WSL restarts (WSL IP changes on restart).
#
# Usage:  bash scripts/find-wsl-ip.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"
source "${SCRIPT_DIR}/cloudflare.config.sh"

# ── Get WSL IP ─────────────────────────────────────────────────────────────────
get_wsl_ip() {
    # Primary: hostname -I (first address)
    local IP; IP="$(hostname -I 2>/dev/null | awk '{print $1}' | tr -d '[:space:]')"
    if [[ -n "$IP" && "$IP" != "127.0.0.1" ]]; then echo "$IP"; return; fi

    # Fallback: ip route
    IP="$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[\d.]+' | head -1 || true)"
    if [[ -n "$IP" ]]; then echo "$IP"; return; fi

    # Fallback: eth0
    IP="$(ip addr show eth0 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1 | head -1 || true)"
    if [[ -n "$IP" ]]; then echo "$IP"; return; fi

    echo "127.0.0.1"
}

# ── Get Public IP ──────────────────────────────────────────────────────────────
get_public_ip() {
    curl -sSf --max-time 5 https://api.ipify.org 2>/dev/null \
    || curl -sSf --max-time 5 https://icanhazip.com 2>/dev/null \
    || echo "unavailable"
}

# ── Get Tailscale IP ──────────────────────────────────────────────────────────
get_tailscale_ip() {
    if command -v tailscale &>/dev/null; then
        tailscale ip --4 2>/dev/null || echo "not-connected"
    else
        echo "not-installed"
    fi
}

# ── Main ───────────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo -e "${BOLD}${CYAN}═══════════════════════════════════════════${RESET}"
    echo -e "${BOLD}${CYAN}  Colony — WSL Network Info${RESET}"
    echo -e "${BOLD}${CYAN}═══════════════════════════════════════════${RESET}"
    echo ""

    WSL_IP="$(get_wsl_ip)"
    PUBLIC_IP="$(get_public_ip)"
    TAILSCALE_IP="$(get_tailscale_ip)"

    echo -e "${BOLD}Network addresses:${RESET}"
    echo -e "  WSL IP:       ${GREEN}${WSL_IP}${RESET}       (local, changes on WSL restart)"
    echo -e "  Public IP:    ${CYAN}${PUBLIC_IP}${RESET}     (your router's external IP)"
    echo -e "  Tailscale IP: ${CYAN}${TAILSCALE_IP}${RESET}  (stable, never changes)"

    echo ""
    echo -e "${BOLD}Local service URLs (WSL IP):${RESET}"
    echo -e "  Coolify:         http://${WSL_IP}:${LOCAL_PORT_COOLIFY}"
    echo -e "  Supabase Studio: http://${WSL_IP}:${LOCAL_PORT_STUDIO}"
    echo -e "  Supabase API:    http://${WSL_IP}:${LOCAL_PORT_SUPABASE}"
    echo -e "  API:             http://${WSL_IP}:${LOCAL_PORT_API}"
    echo -e "  Admin:           http://${WSL_IP}:${LOCAL_PORT_ADMIN}"

    # ── Write .env.local ───────────────────────────────────────────────────────
    ENV_LOCAL="${BACKEND_DIR}/.env.local"
    cat > "$ENV_LOCAL" <<ENVEOF
# .env.local — auto-generated by find-wsl-ip.sh
# DO NOT manually edit — regenerated on each WSL session.
# For permanent public URLs use .env.tunnel instead.

WSL_IP=${WSL_IP}
PUBLIC_IP=${PUBLIC_IP}
TAILSCALE_IP=${TAILSCALE_IP}

COOLIFY_LOCAL=http://${WSL_IP}:${LOCAL_PORT_COOLIFY}
STUDIO_LOCAL=http://${WSL_IP}:${LOCAL_PORT_STUDIO}
SUPABASE_API_LOCAL=http://${WSL_IP}:${LOCAL_PORT_SUPABASE}
API_LOCAL=http://${WSL_IP}:${LOCAL_PORT_API}
ADMIN_LOCAL=http://${WSL_IP}:${LOCAL_PORT_ADMIN}
ENVEOF

    echo ""
    echo -e "${GREEN}✓${RESET}  .env.local updated: ${ENV_LOCAL}"

    # ── Permanent tunnel URLs ──────────────────────────────────────────────────
    if [[ -f "${BACKEND_DIR}/.env.tunnel" ]]; then
        echo ""
        echo -e "${BOLD}Permanent tunnel URLs (from .env.tunnel):${RESET}"
        source "${BACKEND_DIR}/.env.tunnel"
        echo -e "  API:     ${CYAN}${API_URL}${RESET}"
        echo -e "  Studio:  ${CYAN}${STUDIO_URL}${RESET}"
        echo -e "  Coolify: ${CYAN}${COOLIFY_URL}${RESET}"
    fi

    echo ""
    echo -e "${BOLD}${CYAN}═══════════════════════════════════════════${RESET}"
    echo ""
}
main "$@"
